collections:
  project_learn_auth_with_golang:
    output: true
    permalink: /projects/learn-auth-with-golang/:title
  resources_dev_setup_guides:
    output: true
    permalink: /resources/dev-setup/:title
  resources_golang_guides:
    output: true
    permalink: /resources/golang/:title


kramdown:
    auto_ids: true

# plugins:
#   - jekyll-sitemap
