collections:
  project_python_framework:
    output: true
    permalink: /projects/python-framework/:title
  resources_dev_setup_guides:
    output: true
    permalink: /resources/dev-setup/:title


kramdown:
    auto_ids: true

# plugins:
#   - jekyll-sitemap
